import { jitsuToSegment, removeEmptyFields, segmentToTable } from "../src";

test("test segment mapping", () => {
  let event = {
    _timestamp: "2021-12-23T15:18:36.173670Z",
    api_key: "js.gpon6lmpwquappfl07tuq.3lput6s25gycztzcxtodom",
    app: "jitsu_cloud",
    buildId: "b=dev;sc=unknown/unknown;t=2021-12-22T05:55:18.197Z",
    click_id: {},
    doc_encoding: "UTF-8",
    doc_host: "jitsu.com",
    doc_path: "/",
    doc_search: "",
    event_type: "site_page",
    eventn_ctx_event_id: "7a6adc9a-57ff-4d56-8e51-6981561b833e",
    ids: {
      ga: "GA1.2.661874704.1640081071",
    },
    local_tz_offset: -180,
    page_title: "Jitsu : Open Source Data Integration Platform",
    referer: "",
    screen_resolution: "2560x1440",
    source_ip: "172.17.0.1",
    src: "jitsu",
    sysFeatures: {
      anonymizeUsers: false,
      authorization: "firebase",
      billingEnabled: true,
      chatSupportType: "chat",
      createDemoDatabase: true,
      default_s3_bucket: true,
      docker_hub_id: "jitsu",
      enableCustomDomains: true,
      environment: "jitsu_cloud",
      selfhosted: false,
      show_become_user: true,
      smtp: false,
      support_tracking_domains: true,
      support_widget: true,
      telemetry_usage_disabled: false,
      users: true,
    },
    url: "https://jitsu.com/",
    user: {
      anonymous_id: "9a0litvypo",
      email: "vladimir@jitsu.com",
      hashed_anonymous_id: "d0a94aafed3a91d45bceea4e2fa78b3e",
      internal_id: "HweSJ5ytjsWT9JeciVsa3aWj7613",
    },
    user_agent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
    user_language: "en-US",
    utc_time: "2021-12-23T15:18:35.716000Z",
    utm: {
      source: "utm_source_value",
    },
    vp_size: "1708x980",
  };

  let segmentEvent = jitsuToSegment(event);
  console.log("Segment event:", segmentEvent);
  let segmentTable = segmentToTable(segmentEvent, event);
  console.log("Segment table entry:", JSON.stringify(segmentTable, null, 2));
  expect(segmentEvent).toStrictEqual({
    type: "track",
    _metadata: {},
    anonymousId: "9a0litvypo",
    context: {
      ip: "172.17.0.1",
      locale: "en-US",
      userAgent:
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
      page: {
        path: "/",
        referrer: "",
        search: "",
        title: "Jitsu : Open Source Data Integration Platform",
        url: "https://jitsu.com/",
      },
      campaign: {
        source: "utm_source_value",
      },
    },
    event: "site_page",
    name: "",
    properties: {
      api_key: "js.gpon6lmpwquappfl07tuq.3lput6s25gycztzcxtodom",
      app: "jitsu_cloud",
      buildId: "b=dev;sc=unknown/unknown;t=2021-12-22T05:55:18.197Z",
      doc_encoding: "UTF-8",
      doc_host: "jitsu.com",
      ids_ga: "GA1.2.661874704.1640081071",
      local_tz_offset: -180,
      screen_resolution: "2560x1440",
      src: "jitsu",
      sysFeatures_anonymizeUsers: false,
      sysFeatures_authorization: "firebase",
      sysFeatures_billingEnabled: true,
      sysFeatures_chatSupportType: "chat",
      sysFeatures_createDemoDatabase: true,
      sysFeatures_default_s3_bucket: true,
      sysFeatures_docker_hub_id: "jitsu",
      sysFeatures_enableCustomDomains: true,
      sysFeatures_environment: "jitsu_cloud",
      sysFeatures_selfhosted: false,
      sysFeatures_show_become_user: true,
      sysFeatures_smtp: false,
      sysFeatures_support_tracking_domains: true,
      sysFeatures_support_widget: true,
      sysFeatures_telemetry_usage_disabled: false,
      sysFeatures_users: true,
      vp_size: "1708x980",
    },
    sentAt: new Date("2021-12-23T15:18:35.716Z"),
    timestamp: new Date("2021-12-23T15:18:35.716Z"),
    traits: {
      email: "vladimir@jitsu.com",
      hashed_anonymous_id: "d0a94aafed3a91d45bceea4e2fa78b3e",
      internal_id: "HweSJ5ytjsWT9JeciVsa3aWj7613",
    },
    userId: "vladimir@jitsu.com",
  });
  removeEmptyFields(segmentTable);
  //this field changes all the time, so it doesn't make sense to check it
  delete segmentTable["context_library_version"];
  expect(segmentTable).toStrictEqual({
    JITSU_TABLE_NAME: "tracks",
    __sql_type_timestamp: "timestamp",
    __sql_type_sent_at: "timestamp",
    anonymous_id: "9a0litvypo",
    context_campaign_source: "utm_source_value",
    context_ip: "172.17.0.1",
    context_library_name: "jitsu-bridge",
    context_locale: "en-US",
    context_page_path: "/",
    context_page_referrer: "",
    context_page_search: "",
    context_page_title: "Jitsu : Open Source Data Integration Platform",
    context_page_url: "https://jitsu.com/",
    context_user_agent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
    context_utm_source: "utm_source_value",
    email: "vladimir@jitsu.com",
    path: "/",
    referrer: "",
    search: "",
    sent_at: '"2021-12-23T15:18:35.716Z"',
    timestamp: '"2021-12-23T15:18:35.716Z"',
    title: "Jitsu : Open Source Data Integration Platform",
    url: "https://jitsu.com/",
    user_id: "vladimir@jitsu.com",
    api_key: "js.gpon6lmpwquappfl07tuq.3lput6s25gycztzcxtodom",
    app: "jitsu_cloud",
    buildId: "b=dev;sc=unknown/unknown;t=2021-12-22T05:55:18.197Z",
    doc_encoding: "UTF-8",
    doc_host: "jitsu.com",
    ids_ga: "GA1.2.661874704.1640081071",
    local_tz_offset: -180,
    screen_resolution: "2560x1440",
    src: "jitsu",
    sysFeatures_anonymizeUsers: false,
    sysFeatures_authorization: "firebase",
    sysFeatures_billingEnabled: true,
    sysFeatures_chatSupportType: "chat",
    sysFeatures_createDemoDatabase: true,
    sysFeatures_default_s3_bucket: true,
    sysFeatures_docker_hub_id: "jitsu",
    sysFeatures_enableCustomDomains: true,
    sysFeatures_environment: "jitsu_cloud",
    sysFeatures_selfhosted: false,
    sysFeatures_show_become_user: true,
    sysFeatures_smtp: false,
    sysFeatures_support_tracking_domains: true,
    sysFeatures_support_widget: true,
    sysFeatures_telemetry_usage_disabled: false,
    sysFeatures_users: true,
    vp_size: "1708x980",
  });
});
