import { ProjectTemplate } from "./template"
import pkg from "../../package.json"

export type DestinationTemplateVars = {
  license: "MIT" | "Other"
  packageName: string
}

export const destinationProjectTemplate: ProjectTemplate<DestinationTemplateVars> = {
  "tests/adapter.ts": vars => {
    return `
import { adapter } from "../src/adapter"
import { JitsuContext } from "@jitsu/jitsu-types/src/destination"
import { testDestination } from "@jitsu/jitsu-types"

const testContext: JitsuContext = {
  destinationId: "test",
  destinationType: "mydest",
}

testDestination({
  name: "basic",
  context: testContext,
  transform: adapter,
  event: {
    a: 1
  },
  expectedResult: {
    method: "POST",
    url: "https://example.com/api/page",
    headers: {
      "Content-Type": "application/json",
    },
    body: { a: 2 },
  },
})
`
  },
  "src/adapter.ts": vars => {
    return `
import {DestinationMessage, JitsuContext} from "@jitsu/jitsu-types/src/destination";
import {JitsuEvent} from "@jitsu/jitsu-types/src/event";

export default function jitsuAdapter(event: JitsuEvent, dstContext: JitsuContext) {
  return {url: 'https://test.com', method: 'POST', body: {a: (event.a || 0) + 1}} 
}
`
  },
  "src/index.ts": vars =>
    `
import {DestinationAdapter, DestinationDescriptor} from "@jitsu/jitsu-types/src/destination";
import jitsuAdapter from "./adapter";

const adapter: DestinationAdapter = jitsuAdapter

const descriptor: DestinationDescriptor = {
    type: "${vars.packageName}",
    displayName: "${vars.packageName}",
    icon: "",
    description: "Jitsu Destination - ${vars.packageName} (generated by 'jitsu destination create'",
    configurationParameters: [
       //put configuration here
    ]
}

export {descriptor, adapter}
`,
  "package.json": vars => ({
    name: `${vars.packageName}`,
    version: "0.0.1",
    description: `Jitsu Destination - ${vars.packageName}`,
    main: `dist/${vars.packageName}.js`,
    scripts: {
      build: "jitsu destination build",
      test: "jitsu destination test",
    },
    dependencies: {
      "@jitsu/jitsu-cli": `^${pkg.version}`,
      "@jitsu/jitsu-types": `^${pkg.version}`,
      tslib: "^2.3.1",
      typescript: "^4.5.2",
    },
  }),
}
