name: Jitsu SDK

on:
  push:
    # Trigger this workflow on all branches
    branches:
      - '**'
jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Init dagger (dagger project init)
        uses: dagger/dagger-for-github@v2
        with:

          args: project init (dagger do build)
      - name: Build with dagger
        uses: dagger/dagger-for-github@v2
        with:
          args: do build