name: todoapp

on:
  push:
    # Trigger this workflow on all branches
    branches:
      - '*'

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build and test
        uses: dagger/dagger-for-github@v2
        with:
          args: do build