name: Jitsu SDK

on:
  push:
    # Trigger this workflow on all branches
    branches:
      - 'main'
jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Init dagger (dagger project init)
        uses: dagger/dagger-for-github@v3
        with:
          args: dagger project init

      - name: Update dagger (dagger project update)
        uses: dagger/dagger-for-github@v3
        with:
          args: dagger project update

      - name: Build with dagger (dagger do build)
        uses: dagger/dagger-for-github@v3
        with:
          args: dagger do test